# service node type, [DN|CN|LOG]
service-type = "LOG"
data-dir = "/mo-data"

[log]
level = "info"
format = "console"
max-size = 512
filename = "/logs/logservice.log"

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "MINIO"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://obs-proxy:9000"
key-prefix = "server/data"
key-id = "minio"
key-secret = "minio123"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "/mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "MINIO"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://obs-proxy:9000"
key-prefix = "server/etl"
key-id = "minio"
key-secret = "minio123"

[observability]
disableMetric = false
enable-metric-to-prom = true
status-port = 7001
