service-type = "DN"
data-dir = "/mo-data"

[log]
level = "info"
format = "console"
max-size = 512
filename = "/logs/tn.log"

[hakeeper-client]
service-addresses = [
  "mo-log:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "MINIO"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://obs-proxy:9000"
key-prefix = "server/data"
key-id = "minio"
key-secret = "minio123"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "/mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "MINIO"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://obs-proxy:9000"
key-prefix = "server/etl"
key-id = "minio"
key-secret = "minio123"

[observability]
disableTrace = true
disableMetric = false
enable-metric-to-prom = true
status-port = 7001

[dn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bd"
port-base = 19100
service-address = "mo-tn:19100"
service-host = "mo-tn"

[dn.Txn.Storage]
backend = "TAE"
log-backend = "logservice"

[dn.Ckp]
flush-interval = "60s"
min-count = 100
scan-interval = "5s"
incremental-interval = "60s"
global-interval = "100000s"

[dn.GCCfg]
cache-size = 33554432
gc-delete-batch-size = 1
